<a href="https://colab.research.google.com/github/priteshkakani/DataSciencePractice/blob/main/NumPy_Arrays_and_Operations_1.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

# NumPy
NumPy is a Linear Algebra Library in Python and it is the holy grail and the main building block of Data Science using Python. Almost all the libraries in the PyData Ecosystem rely on NumPy as one of their main building blocks.

It is bound to several C libraries which makes NumPy one of the fastest libraries in Python.

We will learn the basics of NumPy, to get started we need to install it!

## Installation Instructions

**It is highly recommended you install Python using the Anaconda distribution to make sure all underlying dependencies (such as Linear Algebra libraries) all sync up with the use of a conda install. If you don't have Anaconda, install NumPy by going to your terminal or command prompt and type:**
    
    !pip install numpy
    conda install numpy
    


In [ ]:
!pip install numpy

## Using NumPy

Once you've installed NumPy you can import it as a library:

In [ ]:
import numpy as np

Numpy has many built-in functions and capabilities. We won't cover them all but instead we will focus on some of the most important aspects of Numpy: vectors,arrays,matrices, and number generation.

# Numpy Arrays

Numpy Arrays are commonly used data structure in python that store data as a grid or matrix and easy to access.

Numpy arrays essentially of two types: vectors and matrices. Vectors are strictly 1-D arrays and matrices are 2-D (Note: A matrix can still have only one row or one column).

The following cells explain on creation of NumPy arrays.

## Creating NumPy Arrays

### From a Python List

An array can be created by directly converting a list or list of lists:

In [ ]:
import numpy as np

In [ ]:
arr1 = np.array([])   # create an empty array
arr1

array([], dtype=float64)

In [ ]:
l1=[]
l1

[]

In [ ]:
my_list = [1,2,3,4,5]
print(my_list)
print(type(my_list))

[1, 2, 3, 4, 5]
<class 'list'>


In [ ]:
a=np.array(my_list)

In [ ]:
a

array([1, 2, 3, 4, 5])

In [ ]:
type(a)   # ndarray is number dimension array

numpy.ndarray

In [ ]:
a.ndim  # number of dimensions in the array

1

In [ ]:
a.size  # size of an array is the no. of items

5

In [ ]:
a.shape # shape of array

(5,)

In [ ]:
li = [11,2,3,1,5,67]
li

[11, 2, 3, 1, 5, 67]

In [ ]:
array1 = np.array(li)
print(array1)

[11  2  3  1  5 67]


#### Arrays can be of n dimensions.

A matrix is a two-dimensional data structure where numbers are arranged into rows and columns.

In [ ]:
my_matrix = [[1,2,3,4],[5,6,7,8],[9,10,11,12]] # list of lists
my_matrix

[[1, 2, 3, 4], [5, 6, 7, 8], [9, 10, 11, 12]]

In [ ]:
b=np.array(my_matrix) # generates a 2-d array
b

array([[[ 1,  2,  3,  4],
        [ 5,  6,  7,  8],
        [ 9, 10, 11, 12]]])

In [ ]:
# Array summary
print('The Dimension of array',b.ndim) # dimensions of given array

The Dimension of array 3


In [ ]:
print('The size of array:',b.size) # Number of elements in array

The size of array: 12


In [ ]:
print('The datatype of element:',b.dtype) # Datatype of elements in array

The datatype of element: int32


In [ ]:
print('The type of structure:',type(b))

The type of structure: <class 'numpy.ndarray'>


In [ ]:
print('The shape:',b.shape)

The shape: (1, 3, 4)


In [ ]:
arr1= np.array([[[1,2,3],[4,5,6]], [[7,8,9],[10,11,12]]])
arr1

array([[[ 1,  2,  3],
        [ 4,  5,  6]],

       [[ 7,  8,  9],
        [10, 11, 12]]])

In [ ]:
arr1.shape

(2, 2, 3)

In [ ]:
arr1.ndim

3

## Built-in Methods

There are lots of built-in ways to generate Arrays

### Reshape function

In [ ]:
arr1

array([[[ 1,  2,  3],
        [ 4,  5,  6]],

       [[ 7,  8,  9],
        [10, 11, 12]]])

In [ ]:
arr1.shape

(2, 2, 3)

In [ ]:
arr1.size

12

In [ ]:
arr1.reshape(4,3) # reshaping array in 2D

array([[ 1,  2,  3],
       [ 4,  5,  6],
       [ 7,  8,  9],
       [10, 11, 12]])

In [ ]:
arr1.reshape(8,2)

ValueError: cannot reshape array of size 12 into shape (8,2)

Task:- Reshape arr1 in all possible dimension

In [ ]:
arr2=arr1.reshape((1,1,1,1,5))  # reshaping the array
# by changing  the dimension i.e 5D

In [ ]:
arr1.ndim

In [ ]:
arr3 =arr1.reshape(-1) # Convert multidimensional array to 1-D array

In [ ]:
arr3.ndim

### arange

Return evenly spaced values within a given interval.

In [ ]:
np.arange(15) # end; default start at 0

In [ ]:
np.arange(2,15) # start, end and step

In [ ]:
np.arange(0,10,2) # start end and step

### zeros and ones

Generate arrays of zeros or ones

In [ ]:
np.zeros(3) # Generates array in 1 dimension with all elements 0

In [ ]:
np.zeros((5,5))  # Generates array in 2 diemnsions with all elements 0

In [ ]:
np.zeros((4,5,2))  # no of elements in each dimension in backward direction
# 2--> 1D ,5-->2D,  4-->3D

In [ ]:
np.ones(3) # Generates array of 1 dimension where all elements are 1

In [ ]:
np.ones((4,6)) # Generates array of 2 dimensions where all elements are 1

### linspace
Return evenly spaced numbers over a specified interval.

In [ ]:
np.linspace(1,15)  # default 50 observations
# both the start and end are included in the array

In [ ]:
np.linspace(5,25,num=10,retstep=True)  # equally spaced 10 values

In [ ]:
# retstep ~ return stepsize computed by linspace

In [ ]:
np.linspace(0,25, retstep=True) # Start # end (Here end is included)
#and default elements are 50

In [ ]:
np.linspace(0,200,10) # default retstep=False

In [ ]:
np.linspace(0,200,10,retstep=True)

### eye

- Creates an identity matrix
- Diagonal elements are 1

In [ ]:
np.eye(5)   # generates 2d array of (5,5)

### Broadcasting in an array

#### The ability to access each and every element of an array is known as Broadcasting.

In [ ]:
l1 = [1,2,3,4]

In [ ]:
l1

In [ ]:
l1 * 5

In [ ]:
big_one=np.ones((3,4))
print(big_one)

In [ ]:
big_one.dtype

In [ ]:
big_one * 3

In [ ]:
bigger_one=big_one*6 - 2
bigger_one

In [ ]:
bigger=np.array(big_one*3 - 0.4, dtype='int')
print(bigger)

In [ ]:
bigger.dtype

In [ ]:
type(bigger)

In [ ]:
bigger.shape

In [ ]:
arr1

## Arithmetic operations on Array

In [ ]:
arr=np.arange(0,20)

In [ ]:
arr

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19])

In [ ]:
arr + arr  # Addition of two arrays

array([ 0,  2,  4,  6,  8, 10, 12, 14, 16, 18, 20, 22, 24, 26, 28, 30, 32,
       34, 36, 38])

In [ ]:
arr * arr #Multiplication of two arrays

array([  0,   1,   4,   9,  16,  25,  36,  49,  64,  81, 100, 121, 144,
       169, 196, 225, 256, 289, 324, 361])

In [ ]:
arr - arr  # Subtraction of two array

array([0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0])

In [ ]:
arr / arr # Division of two array

C:\Users\Datamites\AppData\Local\Temp\ipykernel_12368\3441291647.py:1: RuntimeWarning: invalid value encountered in divide
  arr / arr # Division of two array


array([nan,  1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.,
        1.,  1.,  1.,  1.,  1.,  1.,  1.])

In [ ]:
1/arr  #reciprocal

C:\Users\Datamites\AppData\Local\Temp\ipykernel_12368\2402824131.py:1: RuntimeWarning: divide by zero encountered in divide
  1/arr  #reciprocal


array([       inf, 1.        , 0.5       , 0.33333333, 0.25      ,
       0.2       , 0.16666667, 0.14285714, 0.125     , 0.11111111,
       0.1       , 0.09090909, 0.08333333, 0.07692308, 0.07142857,
       0.06666667, 0.0625    , 0.05882353, 0.05555556, 0.05263158])

In [ ]:
arr **3

array([   0,    1,    8,   27,   64,  125,  216,  343,  512,  729, 1000,
       1331, 1728, 2197, 2744, 3375, 4096, 4913, 5832, 6859], dtype=int32)

In [ ]:
arr %3

array([0, 1, 2, 0, 1, 2, 0, 1, 2, 0, 1, 2, 0, 1, 2, 0, 1, 2, 0, 1],
      dtype=int32)

### Use of Copy function

In [ ]:
arr = np.array([1,2,3,4,5,6,7,8,9,10,11,12,13,14,15,16,17,18,19,20])
arr

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16, 17,
       18, 19, 20])

In [ ]:
arr2 = arr
arr2

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16, 17,
       18, 19, 20])

In [ ]:
arr2[1:6] = 100

In [ ]:
arr2

array([  1, 100, 100, 100, 100, 100,   7,   8,   9,  10,  11,  12,  13,
        14,  15,  16,  17,  18,  19,  20])

In [ ]:
arr

array([  1, 100, 100, 100, 100, 100,   7,   8,   9,  10,  11,  12,  13,
        14,  15,  16,  17,  18,  19,  20])

Now note the changes also occur in our original   array.So to take backups donot use assignment operator.Instead use copy fuction.

In [ ]:
arr3 = arr.copy() # generate a copy / creates a backup

In [ ]:
arr3

array([  1, 100, 100, 100, 100, 100,   7,   8,   9,  10,  11,  12,  13,
        14,  15,  16,  17,  18,  19,  20])

In [ ]:
arr3[1:6] = 500
arr3

array([  1, 500, 500, 500, 500, 500,   7,   8,   9,  10,  11,  12,  13,
        14,  15,  16,  17,  18,  19,  20])

In [ ]:
arr  # copy function retains the original. copy creates a backup array.

array([  1, 100, 100, 100, 100, 100,   7,   8,   9,  10,  11,  12,  13,
        14,  15,  16,  17,  18,  19,  20])

In [ ]:
id(arr)

2773380946256

In [ ]:
id(arr2)

2773380946256

In [ ]:
id(arr3)

2773380947024

## Random number generation

Numpy also has lots of ways to create random number arrays:

### rand
Create an array of the given shape and populate it with
random samples from a uniform distribution
over ``[0, 1)``.

In [ ]:
np.random.rand()

0.09208139236577273

In [ ]:
np.random.rand(10) # rand gives values between 0 and 1

array([0.80299876, 0.28452493, 0.94891575, 0.7251671 , 0.63181441,
       0.80711638, 0.4635487 , 0.19768443, 0.74093684, 0.22555695])

In [ ]:
np.random.rand(5,2)

array([[0.25959593, 0.01758784],
       [0.87380047, 0.49394468],
       [0.20453404, 0.89997901],
       [0.28070346, 0.35342389],
       [0.01030008, 0.1519607 ]])

In [ ]:
# Creating array from uniform distribution
new_arr=np.random.rand(5,3,2)
# 3 dimensional array of shape (5,3,2)

In [ ]:
new_arr

array([[[0.10230739, 0.62369227],
        [0.32834691, 0.16529055],
        [0.04759791, 0.43395644]],

       [[0.32707123, 0.27750596],
        [0.24266157, 0.69702733],
        [0.0766651 , 0.56222152]],

       [[0.4809184 , 0.14638078],
        [0.79706667, 0.60848518],
        [0.30700927, 0.80383148]],

       [[0.15892159, 0.99071093],
        [0.95235361, 0.638323  ],
        [0.23418316, 0.29183254]],

       [[0.95188475, 0.61294577],
        [0.82219027, 0.02678759],
        [0.63514774, 0.95876053]]])

In [ ]:
np.random.rand(3,3,1,2)  #4D array

array([[[[0.10504603, 0.54374483]],

        [[0.17126573, 0.54034906]],

        [[0.94429884, 0.03257877]]],


       [[[0.82301449, 0.89274957]],

        [[0.91530649, 0.92619421]],

        [[0.77338337, 0.66871895]]],


       [[[0.67196554, 0.16731566]],

        [[0.18077408, 0.69853402]],

        [[0.85104849, 0.58809884]]]])

### randn

Return a sample (or samples) from the "standard normal" distribution. Unlike rand which is uniform:

##### For randn, random numbbers generated will be in approximately -3 to +3 range.

In [ ]:
arr1=np.random.randn(5)  # 5 observations from std normal distribution
arr1

array([-2.48450892e-04, -9.02762211e-01, -4.44242710e-01,  4.62908140e-01,
       -1.10167789e+00])

In [ ]:
np.mean(arr1)

-0.3972046252058743

In [ ]:
np.std(arr1)

0.5747089372767723

### randint
Return random integers from `low` (inclusive) to `high` (exclusive).

In [ ]:
np.random.randint(1,100)
# third argument is no. of values. default =1 value

79

In [ ]:
np.random.randint(1,100,10)

array([24,  2, 26, 80, 53, 83,  2, 95, 61, 13])

In [ ]:
np.random.randint(40,60,size=50) # generating 50 values between

array([59, 43, 54, 55, 58, 53, 46, 44, 47, 46, 59, 43, 50, 58, 59, 55, 59,
       46, 40, 47, 40, 51, 55, 46, 53, 51, 49, 57, 56, 51, 42, 53, 52, 50,
       42, 53, 45, 51, 41, 52, 56, 41, 44, 50, 45, 48, 40, 41, 42, 57])

## Universal Array Function


In [ ]:
arr

array([  1, 100, 100, 100, 100, 100,   7,   8,   9,  10,  11,  12,  13,
        14,  15,  16,  17,  18,  19,  20])

In [ ]:
np.add(arr,3) ## add 3 to array

array([  4, 103, 103, 103, 103, 103,  10,  11,  12,  13,  14,  15,  16,
        17,  18,  19,  20,  21,  22,  23])

In [ ]:
np.sum(arr)

690

In [ ]:
np.sqrt(arr)

array([ 1.        , 10.        , 10.        , 10.        , 10.        ,
       10.        ,  2.64575131,  2.82842712,  3.        ,  3.16227766,
        3.31662479,  3.46410162,  3.60555128,  3.74165739,  3.87298335,
        4.        ,  4.12310563,  4.24264069,  4.35889894,  4.47213595])

In [ ]:
np.cbrt(arr)

array([1.        , 4.64158883, 4.64158883, 4.64158883, 4.64158883,
       4.64158883, 1.91293118, 2.        , 2.08008382, 2.15443469,
       2.22398009, 2.28942849, 2.35133469, 2.41014226, 2.46621207,
       2.5198421 , 2.57128159, 2.62074139, 2.66840165, 2.71441762])

In [ ]:
np.exp(arr) # calculating exponential

array([2.71828183e+00, 2.68811714e+43, 2.68811714e+43, 2.68811714e+43,
       2.68811714e+43, 2.68811714e+43, 1.09663316e+03, 2.98095799e+03,
       8.10308393e+03, 2.20264658e+04, 5.98741417e+04, 1.62754791e+05,
       4.42413392e+05, 1.20260428e+06, 3.26901737e+06, 8.88611052e+06,
       2.41549528e+07, 6.56599691e+07, 1.78482301e+08, 4.85165195e+08])

In [ ]:
np.sin(arr)

array([ 0.84147098, -0.50636564, -0.50636564, -0.50636564, -0.50636564,
       -0.50636564,  0.6569866 ,  0.98935825,  0.41211849, -0.54402111,
       -0.99999021, -0.53657292,  0.42016704,  0.99060736,  0.65028784,
       -0.28790332, -0.96139749, -0.75098725,  0.14987721,  0.91294525])

In [ ]:
np.cos(arr)

array([ 0.54030231,  0.86231887,  0.86231887,  0.86231887,  0.86231887,
        0.86231887,  0.75390225, -0.14550003, -0.91113026, -0.83907153,
        0.0044257 ,  0.84385396,  0.90744678,  0.13673722, -0.75968791,
       -0.95765948, -0.27516334,  0.66031671,  0.98870462,  0.40808206])

In [ ]:
np.tan(arr)

array([ 1.55740772e+00, -5.87213915e-01, -5.87213915e-01, -5.87213915e-01,
       -5.87213915e-01, -5.87213915e-01,  8.71447983e-01, -6.79971146e+00,
       -4.52315659e-01,  6.48360827e-01, -2.25950846e+02, -6.35859929e-01,
        4.63021133e-01,  7.24460662e+00, -8.55993401e-01,  3.00632242e-01,
        3.49391565e+00, -1.13731371e+00,  1.51589471e-01,  2.23716094e+00])

In [ ]:
np.log(arr)

array([0.        , 4.60517019, 4.60517019, 4.60517019, 4.60517019,
       4.60517019, 1.94591015, 2.07944154, 2.19722458, 2.30258509,
       2.39789527, 2.48490665, 2.56494936, 2.63905733, 2.7080502 ,
       2.77258872, 2.83321334, 2.89037176, 2.94443898, 2.99573227])

### max,min,argmax,argmin

These are useful methods for finding max or min values. Or to find their index locations using argmin or argmax

In [ ]:
arr2=np.random.randint(1,100,20)

In [ ]:
arr2

array([23, 50, 54, 86, 84, 73, 81, 13, 70, 45, 81, 16, 99, 24, 33, 15, 40,
       59,  2, 28])

In [ ]:
arr2.max() # gives maximum values of element

99

In [ ]:
arr2.min() # gives minimum values of element

2

In [ ]:
arr2.argmax() # gives index location of maximum value


12

In [ ]:
arr2.argmin() # gives index location of minimum value

18

# Happy Learning!